name: Tag and release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@9eefd77e4e64f4b149710554560fb43f4a2f35b0 # v1.0.28
    secrets: inherit
